//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapHanaEf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration; 
    
    public class IduEfConfigurations  {
    	public static DbModelBuilder SetConfigurations(DbModelBuilder builder, string schemaName)
        {
    		builder.Configurations.Add<Tm_Master01>(new Tm_Master01___Map(schemaName));
    		builder.Configurations.Add<Tm_Master02>(new Tm_Master02___Map(schemaName));
    	return builder;
    	}
    }
     
        
    public class Tm_Master01___Map : EntityTypeConfiguration<Tm_Master01>
    {
    	public Tm_Master01___Map(string schemaName)
    	{
    			this.ToTable("Tm_Master01", schemaName); 
    			this.HasKey(a => new { a.Id });
    	}
    }
    
        
    public class Tm_Master02___Map : EntityTypeConfiguration<Tm_Master02>
    {
    	public Tm_Master02___Map(string schemaName)
    	{
    			this.ToTable("Tm_Master02", schemaName); 
    			this.HasKey(a => new { a.Id });
    	}
    }
    
    
    public partial class Entities1 : DbContext
    {
    	/* idu  
        public Entities1()
            : base("name=Entities1")
    	{
    	    }
    
    	idu*/
    
    	//-------------------------
    	//--TAMBAH SENDIRI
    	//-------------------------
    	public Entities1(string nameOrConnectionString, DbCompiledModel model)
            : base(nameOrConnectionString,model)
        { 
    	}
    	//-------------------------
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    	
    
        public virtual DbSet<Tm_Master01> Tm_Master01 { get; set; }
        public virtual DbSet<Tm_Master02> Tm_Master02 { get; set; }
    }
}
